env = Environment()

cflags = ['-O2', '-g']
paths = [
    '../lib/utils',
    '../lib/vhost',
    '.',
]

env.Append(CCFLAGS=cflags)
env.Append(CPPPATH=paths)

obj = env.Object(Glob('*.c'))

Return('obj')
